# Generated by Django 6.0.5 on 2026-06-08 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_veterinarian_appointment_veterinarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_disease', models.CharField(max_length=150)),
                ('validity_months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='PetVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animal.pet')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_vaccinations', to='animal.veterinarian')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_pets', to='animal.vaccine')),
            ],
        ),
    ]
