# Generated by Django 6.0.1 on 2026-06-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='animal.appointment'),
            preserve_default=False,
        ),
    ]
