# Generated by Django 6.0.1 on 2026-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_remove_medicalrecord_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Függőben'), ('scheduled', 'Elfogadva'), ('completed', 'Befejezve'), ('cancelled', 'Lemondva')], default='pending', max_length=20),
        ),
    ]
