# Generated by Django 6.0.1 on 2026-07-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(help_text='Pl.: 2x1 tabletta', max_length=100)),
                ('duration', models.CharField(help_text='Pl.: 7 nap', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='További utasítások')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='animal.medicalrecord')),
            ],
        ),
    ]
